#!/bin/bash

# Default values
verbose=false
target_users_list=$USER
partitions=("krummellab")
all_users=false

# Display help message if --help option is provided
if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
    echo "Usage: $0 [-v] [-u username] [-p \"partition1|partition2|...\"]"
    echo "Usage: $0 [-v] [-a]"
    echo "Sum the number of cores from active jobs for a username."
    echo "If no username is provided, the current \$USER will be used."
    echo "If no partition is provided, the default partition is krummellab."
    echo "If running with -a (all), no username or partition are needed."
    echo ""
    echo "Options:"
    echo "  -v, --verbose         Enable verbose mode"
    echo "  -u, --user username   Specify a username (default: \$USER)"
    echo "  -a, --all             Run for all users running jobs on krummellab"
    echo "  -p, --partition \"partition1|partition2|...\" Specify one or more partitions in quotes, separated by | (default: krummellab)"
    exit 0
fi

# Parse command-line options
while [[ "$#" -gt 0 ]]; do
    case $1 in
        -a|--all) all_users=true ;;
        -p=*|--partition=*) IFS='|' read -ra partitions <<< "${1#*=}";;
        -p|--partition) IFS='|' read -ra partitions <<< "$2"; shift ;;
        -u=*|--user=*) target_users_list="${1#*=}" ;;
        -u|--user) target_users_list="$2"; shift ;;
        -v|--verbose) verbose=true ;;        
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
    shift
done

if [ "$all_users" = true ]; then
    target_users_list=$(squeue | grep krum | awk '{print $4}' | sort | uniq)
fi

if [ "$verbose" = true ]; then
    echo "Counting cores for ("$target_users_list") on the ${partitions[@]} partition."
    echo "This might take a few seconds..."
fi

# Declare an associative array to store sums for each partition
declare -A partition_sums

core_collector() {
    local partition="$1"
    local target_user="$2"

    partition_sums[$partition]=0  # Reset partition sum for the current partition
        


    for monitoring_job_id in $(squeue | grep " R " | grep " R " | grep "${partition:0:8}" | grep "${target_user:0:8}" | awk '{print $1}'); do
        #locate sef
        c4_utils_dir="$(dirname "$0")"
        
        # Use seff to get efficiency and resource usage information for each job
        seff_output=$("$c4_utils_dir/seff" "$monitoring_job_id")
        
        # Extract nodes and cores per node information
        nodes=0
        cores_per_node=0

        nodes=$(echo "$seff_output" | grep -E "Nodes:|Cores:" | awk '{print $2}')

        if echo "$seff_output" | grep -q "per"; then
            cores_per_node=$(echo "$seff_output" | grep -E "Cores per node:" | awk '{print $4}')
        fi
                
        if [[ $cores_per_node =~ ^[1-9][0-9]*$ ]]; then
            partition_sums[$partition]=$((partition_sums[$partition] + (nodes * cores_per_node)))
        else
            partition_sums[$partition]=$((partition_sums[$partition] + nodes))
        fi
    done
}

for target_user in $target_users_list; do
    # Print the individual partition sums
    for partition in "${partitions[@]}"; do
        core_collector "$partition" "$target_user"
        echo "${target_user}'s cores for partition $partition: ${partition_sums[$partition]}"
    done
    
    # Calculate total sum of cores across all partitions
    total_sum=0
    for partition in "${partitions[@]}"; do
        ((total_sum += partition_sums[$partition]))
    done
    
    # Print the total sum
    if [ "${#partitions[@]}" -gt 1 ] && [ "$all_users" = false ]; then
        echo "${target_user}'s total sum cores for all partitions: $total_sum"
    fi
done
